In [2]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1

Yes, there is a difference in the data type of variables list_ and array_list. The list_ variable is a list data structure, whereas the array_list variable is a NumPy array data structure 

In [3]:
print(f"The data type of list_ is {type(list_)}")
print(f"The data type of array_list is {type(array_list)}")


The data type of list_ is <class 'list'>
The data type of array_list is <class 'numpy.ndarray'>


Q2

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

for i in list_:
    print(f"The data type of {i} is {type(i)}")

for i in array_list:
    print(f"The data type of {i} is {type(i)}")


The data type of 1 is <class 'str'>
The data type of 2 is <class 'str'>
The data type of 3 is <class 'str'>
The data type of 4 is <class 'str'>
The data type of 5 is <class 'str'>
The data type of 1 is <class 'numpy.str_'>
The data type of 2 is <class 'numpy.str_'>
The data type of 3 is <class 'numpy.str_'>
The data type of 4 is <class 'numpy.str_'>
The data type of 5 is <class 'numpy.str_'>


Q3

Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. When we create a NumPy array using the np.array() function, we can specify the data type of the array using the dtype parameter.

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

for i in list_:
    print(f"The data type of {i} is {type(i)}")

for i in array_list:
    print(f"The data type of {i} is {type(i)}")


The data type of 1 is <class 'str'>
The data type of 2 is <class 'str'>
The data type of 3 is <class 'str'>
The data type of 4 is <class 'str'>
The data type of 5 is <class 'str'>
The data type of 1 is <class 'numpy.int32'>
The data type of 2 is <class 'numpy.int32'>
The data type of 3 is <class 'numpy.int32'>
The data type of 4 is <class 'numpy.int32'>
The data type of 5 is <class 'numpy.int32'>


Q4

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print(f"The shape of num_array is {num_array.shape}")
print(f"The size of num_array is {num_array.size}")


The shape of num_array is (2, 3)
The size of num_array is 6


Q5

In [10]:
import numpy as np

zeros_array = np.zeros((3, 3))

print(f"The zeros array is:\n{zeros_array}")


The zeros array is:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6

In [12]:
import numpy as np

identity_matrix = np.identity(5)

print(f"The identity matrix is:\n{identity_matrix}")


The identity matrix is:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
